### ISSUE TITLE
Morning Session Code Review

### ISSUE THREAD

**Issue by harlexkhal** [zmekonnen251/portofolio-website#5]
Import the correct font styles used in your css into your HTML headers. click  [here](https://fonts.google.com/) to get  the correct font styles links to include in your HTML header

**Comment by vikipretium** [comment]
![image](https://user-images.githubusercontent.com/20333314/149468197-cb794784-404c-43f4-b2a0-1a856455e444.png)

Hello @zmekonnen251,

What you did in the about section is great, just a small point check. The black background is not fully stretched to the width of the about section.

**Comment by mnekx** [comment]
It is a good design sofar, but one note take. See below screenshot:-
![image](https://user-images.githubusercontent.com/22321030/149471433-0a46c180-346e-4604-810a-3fbe95feaf69.png)

there is a horizontal scroll bar that makes the design not very good. You could fix it with 'overflow: hidden'

**Comment by zmekonnen251** [comment]
Thank you guys for your supportive comments on my project. I will work on the issues you raised. 👍
