### ISSUE TITLE
Peer review - M1W3

### ISSUE THREAD

**Issue by ahangarha** [zmekonnen251/portofolio-website#8]
Peer-Review on PR https://github.com/zmekonnen251/portofolio-website/pull/4

**Comment by daudi13** [comment]
-Please consider adding a max-width on your body element
-Please go through the BEM naming conventions.

**Comment by ahangarha** [comment]
Hi.

Firstly, congratulations for implementation of this design. I see most of things are implemented perfectly. Just there are few issues that I list here:

## header in My Recent Works section
![image](https://user-images.githubusercontent.com/11241315/149889557-645c31c0-eba4-4309-b2d3-c6efb3b9f501.png)
1. Images is distorted
2. The gap between sections is more than what is required in made in the Figma design
3. Button width doesn't follow the design

## Items in Recent Works
![image](https://user-images.githubusercontent.com/11241315/149889929-5f3a4a83-4de0-448e-a820-390a0d9d28b3.png)
Texts should align to the bottom of the item not center.

## Contact Section
The gap between name and email field is more than what it should. lines made for fields are also darker than Figma design.

And just wanted to mention that your implementation in general is very good. No matter how one implement things perfectly, all the time something is being missed :smiley:

**Comment by zmekonnen251** [comment]
Thank you guys for your helpful comments and for showing me the best practices of a CSS selector, which is the BEM technique. 
👍
